version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sarah
      POSTGRES_DB: sarah
      POSTGRES_PASSWORD: password
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d
  web:
    build: .
    container_name: multiuser_dataentry_app
    
volumes:
  database_data:
    driver: local