# Generated by Django 4.1.7 on 2023-02-24 18:08

from django.db import migrations, models
import location_field.models.plain
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=250, unique=True)),
                ('event_date', models.DateTimeField(unique=True)),
                ('event_description', models.TextField()),
                ('event_duration', models.PositiveIntegerField()),
                ('event_guests', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
            options={
                'verbose_name': 'event_detail',
                'db_table': 'event_details',
            },
        ),
        migrations.CreateModel(
            name='HealthInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('zipcode', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'health institution',
                'db_table': 'health_insitution',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('speciality', models.CharField(max_length=250, unique=True)),
                ('years_of_experience', models.IntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume', models.FileField(upload_to='uploads')),
            ],
            options={
                'verbose_name': 'professional_detail',
                'db_table': 'professional_details',
            },
        ),
    ]
