# Generated by Django 4.1.7 on 2023-02-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinstitution',
            name='attribute',
            field=models.JSONField(default={}),
        ),
    ]
