# Generated by Django 4.1.7 on 2023-02-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_healthinstitution_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('definition', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('model_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modeldefinition')),
            ],
        ),
    ]
