# Generated by Django 4.1.7 on 2023-02-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modeldefinition_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='ModelDefinition',
        ),
    ]
